### PR TITLE
Add project info

### PR DESCRIPTION
**Pull request by bbonanno**

### CODE REVIEW

**Comment by mockitoguy** [comment]
Once new version publishes, I'll try to sync it to central.

**Comment by bbonanno** [comment]
@mockitoguy Great! looking forward to see it there :)

**Comment by mockitoguy** [comment]
hmmm, it seems to have worked but I still don't see the artifact under https://repo.maven.apache.org/maven2/org/mockito/mockito-scala_2.12

Let's give it some time to show up in central.

**Comment by bbonanno** [comment]
@mockitoguy it is now! :) https://repo.maven.apache.org/maven2/org/mockito/mockito-scala_2.12/0.0.6/

Where I don't see it is in https://mvnrepository.com/search?q=mockito nor http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.mockito%22

I guess those will sync up at some point?

**Comment by mockitoguy** [comment]
I think so.

**Pull request merged**
