### PR TITLE
bump scala 2.13 to latest milestone (M5)

### PR DESCRIPTION
**Pull request by jozic**

### CODE REVIEW

**Comment by ultrasecreth** [comment]
@jozic Please fix the scalatest dependency

**Comment by jozic** [comment]
i see that more work is required here
will try to address this soon

**Comment by jozic** [comment]
@bbonanno on 2.13.0-M5 vararg tests fail with
```
[info] - should work with varargs and multiple param lists *** FAILED ***
[info]   org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
[info] org.fooWithVarArgAndSecondParameterList(
[info]     eqTo(cow),
[info]     <any>
[info] );
[info] -> at user.org.mockito.IdiomaticMockitoTest.$anonfun$new$71(IdiomaticMockitoTest.scala:431)
[info] 
[info] However, there was exactly 1 interaction with this mock:
[info] org.fooWithVarArgAndSecondParameterList(
[info]     ArraySeq(cow),
[info]     Cheese(Gouda)
[info] );
[info] -> at user.org.mockito.IdiomaticMockitoTest.$anonfun$new$71(IdiomaticMockitoTest.scala:429)
[info]   at user.org.mockito.IdiomaticMockitoTest.$anonfun$new$71(IdiomaticMockitoTest.scala:431)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   ...
```
any suggestions?

**Comment by ultrasecreth** [comment]
@jozic Scala 2.13.0-M5 uses `ArraySeq.ofRef[_]` instead of `mutable.WrappedArray[_]`, so the pattern match for varargs fails, it needs to be updated

**Comment by ultrasecreth** [comment]
@jozic let me know if it gets nasty and I'll take care of it

**Comment by jozic** [comment]
@bbonanno i think i made Travis happy
check the code please

**Comment by ultrasecreth** [comment]
@jozic Looks good!

One thing that worries me a bit is how the different versions of ScalaTest and Scalactic could play as most of the people would be using 3.0.5...

Could you please do an `sbt publishLocal` and verify that adding this new release to an existing project this dependencies do not break anything? (in the meantime I'll try to automate some test like it in Travis)

Cheers

**Comment by jozic** [comment]
@bbonanno 
I can do it, but probably not earlier than Monday. Will post an update here

**Comment by jozic** [comment]
@bbonanno 
I've published new version locally and used that on my project. Works fine.
But my project (maven) specifies version of scalatest as 3.0.5, so mockito-scala can't override it, not sure if this is a good test, but also not sure if anyone else does it differently (not specifying scalatest version)

I also rebased on latest release

**Comment by ultrasecreth** [comment]
@jozic Thanks for that, and that's exactly what I wanted to check, I was afraid of people providing 3.0.5 and having some sort of nasty side effect, but if it works I'm happy to merge it

Many thanks for the contribution, much appreciated

**Pull request merged**
