### PR TITLE
Add yml to build/release using GH Actions

### PR DESCRIPTION
**Pull request by ultrasecreth**
Implements #324

### CODE REVIEW

**Comment by ultrasecreth** [comment]
@mockitoguy mind double-checking this?
I assume that merging it to master won't trigger a release to maven central unless I add `[ci maven-central-release]`, is that correct?

**Comment by mockitoguy** [comment]
This looks great! In order to start releasing to Maven Central we need to change [this line](https://github.com/mockito/mockito-scala/blob/28e35b37594804fc4451165e74b8b36faf0c1b3b/gradle/shipkit.gradle#L45) to read the env variable.

**Review by mockitoguy — APPROVED** [review]
Thanks! See my comment on the PR regarding the maven central release.

**Comment by ultrasecreth** [comment]
> this line

Cool, will do so in a follow-up PR

**Pull request merged**
