### PR TITLE
support Scala 3.x

### PR DESCRIPTION
**Pull request by sullis**
https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html

### CODE REVIEW

**Comment by ultrasecreth** [comment]
Blocked by #329

**Comment by ultrasecreth** [comment]
@sullis mind rebasing on `release/1.x` so the build runs on the PR?

**Comment by ultrasecreth** [comment]
@sullis also pls bump the minor version :)

**Comment by sullis** [comment]
> @sullis also pls bump the minor version :)

Rebase: done.
Version bump: done.

**Comment by ultrasecreth** [comment]
Missing dependencies

- [ ] scala-reflect (may not be necessary in Scala 3)
- [ ] cats-laws
- [ ] discipline-scalatest
- [ ] cats-core
- [ ] specs2-core
- [ ] scalatest
- [ ] scalacheck
- [ ] scalactic

@sullis I'm afraid we're a long way from being able to support Scala 3 (that's assuming that after all this dependencies are available the lib code is still compatible)

**Comment by ultrasecreth** [comment]
Closing this PR as Dotty requires a full re-write of a big chunk of the lib, will raise issues to track that separately

**Pull request closed without merging**
